# 清华 CocoaPods Specs 镜像：https://mirrors.tuna.tsinghua.edu.cn/help/cocoapods/
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '15.0'
inhibit_all_warnings!

# WhiteNeedle: 自动向 App target 添加 Build Phase 注入 Bonjour / Local Network 权限
require_relative '../../ios-dylib/WhiteNeedle/Scripts/cocoapods_hook'

target 'WhiteNeedleExample' do
  # 本地开发 Pod：源码在 ios-dylib/WhiteNeedle，可在 Xcode 中单步调试
  pod 'WhiteNeedle', :path => '../../ios-dylib/WhiteNeedle'

  # 将 test-scripts/ 同步到 app bundle，供运行时加载测试脚本
  script_phase :name => 'Copy Test Scripts',
    :script => 'rsync -av --delete "${SRCROOT}/../../test-scripts/" "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/test-scripts/"',
    :execution_position => :after_compile
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end

  whiteneedle_inject_permissions(installer)
end
